fragment EventiParts on Eventi {
  __typename
  titolo
  data
  categoria
  descrizione
  luogo
  iscrizioniHref
  pubblicato
  titolo_en
  descrizione_en
  luogo_en
  corpo_en
  body
}

fragment InfoParts on Info {
  __typename
  indirizzo
  come_arrivare
  come_arrivare_en
  orari
  orari_en
  telefono
  email
}

fragment PagineParts on Pagine {
  __typename
  title
  description
  hero_eyebrow
  hero_titolo
  hero_titolo_accent
  hero_sottotitolo
  hero_immagine
  hero_immagine_alt
  body
}
