//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  eventi: Eventi;
  eventiConnection: EventiConnection;
  info: Info;
  infoConnection: InfoConnection;
  news: News;
  newsConnection: NewsConnection;
  pagine: Pagine;
  pagineConnection: PagineConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventiArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventiConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventiFilter>;
};


export type QueryInfoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryInfoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<InfoFilter>;
};


export type QueryNewsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNewsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
};


export type QueryPagineArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPagineConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagineFilter>;
};

export type DocumentFilter = {
  eventi?: InputMaybe<EventiFilter>;
  info?: InputMaybe<InfoFilter>;
  news?: InputMaybe<NewsFilter>;
  pagine?: InputMaybe<PagineFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Eventi | Info | News | Pagine | Folder;

export type Eventi = Node & Document & {
  __typename?: 'Eventi';
  titolo: Scalars['String']['output'];
  data: Scalars['String']['output'];
  categoria: Scalars['String']['output'];
  descrizione: Scalars['String']['output'];
  luogo?: Maybe<Scalars['String']['output']>;
  iscrizioniHref?: Maybe<Scalars['String']['output']>;
  pubblicato?: Maybe<Scalars['Boolean']['output']>;
  titolo_en?: Maybe<Scalars['String']['output']>;
  descrizione_en?: Maybe<Scalars['String']['output']>;
  luogo_en?: Maybe<Scalars['String']['output']>;
  corpo_en?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type EventiFilter = {
  titolo?: InputMaybe<StringFilter>;
  data?: InputMaybe<DatetimeFilter>;
  categoria?: InputMaybe<StringFilter>;
  descrizione?: InputMaybe<StringFilter>;
  luogo?: InputMaybe<StringFilter>;
  iscrizioniHref?: InputMaybe<StringFilter>;
  pubblicato?: InputMaybe<BooleanFilter>;
  titolo_en?: InputMaybe<StringFilter>;
  descrizione_en?: InputMaybe<StringFilter>;
  luogo_en?: InputMaybe<StringFilter>;
  corpo_en?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type EventiConnectionEdges = {
  __typename?: 'EventiConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Eventi>;
};

export type EventiConnection = Connection & {
  __typename?: 'EventiConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventiConnectionEdges>>>;
};

export type Info = Node & Document & {
  __typename?: 'Info';
  indirizzo: Scalars['String']['output'];
  come_arrivare: Scalars['String']['output'];
  come_arrivare_en: Scalars['String']['output'];
  orari: Scalars['String']['output'];
  orari_en: Scalars['String']['output'];
  telefono: Scalars['String']['output'];
  email: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type InfoFilter = {
  indirizzo?: InputMaybe<StringFilter>;
  come_arrivare?: InputMaybe<StringFilter>;
  come_arrivare_en?: InputMaybe<StringFilter>;
  orari?: InputMaybe<StringFilter>;
  orari_en?: InputMaybe<StringFilter>;
  telefono?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
};

export type InfoConnectionEdges = {
  __typename?: 'InfoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Info>;
};

export type InfoConnection = Connection & {
  __typename?: 'InfoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<InfoConnectionEdges>>>;
};

export type News = Node & Document & {
  __typename?: 'News';
  titolo: Scalars['String']['output'];
  data: Scalars['String']['output'];
  categoria: Scalars['String']['output'];
  sintesi: Scalars['String']['output'];
  immagine: Scalars['String']['output'];
  immagine_alt: Scalars['String']['output'];
  pubblicato?: Maybe<Scalars['Boolean']['output']>;
  titolo_en?: Maybe<Scalars['String']['output']>;
  categoria_en?: Maybe<Scalars['String']['output']>;
  sintesi_en?: Maybe<Scalars['String']['output']>;
  immagine_alt_en?: Maybe<Scalars['String']['output']>;
  corpo_en?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NewsFilter = {
  titolo?: InputMaybe<StringFilter>;
  data?: InputMaybe<DatetimeFilter>;
  categoria?: InputMaybe<StringFilter>;
  sintesi?: InputMaybe<StringFilter>;
  immagine?: InputMaybe<ImageFilter>;
  immagine_alt?: InputMaybe<StringFilter>;
  pubblicato?: InputMaybe<BooleanFilter>;
  titolo_en?: InputMaybe<StringFilter>;
  categoria_en?: InputMaybe<StringFilter>;
  sintesi_en?: InputMaybe<StringFilter>;
  immagine_alt_en?: InputMaybe<StringFilter>;
  corpo_en?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type NewsConnectionEdges = {
  __typename?: 'NewsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<News>;
};

export type NewsConnection = Connection & {
  __typename?: 'NewsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<NewsConnectionEdges>>>;
};

export type Pagine = Node & Document & {
  __typename?: 'Pagine';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  hero_eyebrow?: Maybe<Scalars['String']['output']>;
  hero_titolo?: Maybe<Scalars['String']['output']>;
  hero_titolo_accent?: Maybe<Scalars['String']['output']>;
  hero_sottotitolo?: Maybe<Scalars['String']['output']>;
  hero_immagine?: Maybe<Scalars['String']['output']>;
  hero_immagine_alt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PagineFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  hero_eyebrow?: InputMaybe<StringFilter>;
  hero_titolo?: InputMaybe<StringFilter>;
  hero_titolo_accent?: InputMaybe<StringFilter>;
  hero_sottotitolo?: InputMaybe<StringFilter>;
  hero_immagine?: InputMaybe<StringFilter>;
  hero_immagine_alt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PagineConnectionEdges = {
  __typename?: 'PagineConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pagine>;
};

export type PagineConnection = Connection & {
  __typename?: 'PagineConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PagineConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateEventi: Eventi;
  createEventi: Eventi;
  updateInfo: Info;
  createInfo: Info;
  updateNews: News;
  createNews: News;
  updatePagine: Pagine;
  createPagine: Pagine;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateEventiArgs = {
  relativePath: Scalars['String']['input'];
  params: EventiMutation;
};


export type MutationCreateEventiArgs = {
  relativePath: Scalars['String']['input'];
  params: EventiMutation;
};


export type MutationUpdateInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: InfoMutation;
};


export type MutationCreateInfoArgs = {
  relativePath: Scalars['String']['input'];
  params: InfoMutation;
};


export type MutationUpdateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationCreateNewsArgs = {
  relativePath: Scalars['String']['input'];
  params: NewsMutation;
};


export type MutationUpdatePagineArgs = {
  relativePath: Scalars['String']['input'];
  params: PagineMutation;
};


export type MutationCreatePagineArgs = {
  relativePath: Scalars['String']['input'];
  params: PagineMutation;
};

export type DocumentUpdateMutation = {
  eventi?: InputMaybe<EventiMutation>;
  info?: InputMaybe<InfoMutation>;
  news?: InputMaybe<NewsMutation>;
  pagine?: InputMaybe<PagineMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  eventi?: InputMaybe<EventiMutation>;
  info?: InputMaybe<InfoMutation>;
  news?: InputMaybe<NewsMutation>;
  pagine?: InputMaybe<PagineMutation>;
};

export type EventiMutation = {
  titolo?: InputMaybe<Scalars['String']['input']>;
  data?: InputMaybe<Scalars['String']['input']>;
  categoria?: InputMaybe<Scalars['String']['input']>;
  descrizione?: InputMaybe<Scalars['String']['input']>;
  luogo?: InputMaybe<Scalars['String']['input']>;
  iscrizioniHref?: InputMaybe<Scalars['String']['input']>;
  pubblicato?: InputMaybe<Scalars['Boolean']['input']>;
  titolo_en?: InputMaybe<Scalars['String']['input']>;
  descrizione_en?: InputMaybe<Scalars['String']['input']>;
  luogo_en?: InputMaybe<Scalars['String']['input']>;
  corpo_en?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type InfoMutation = {
  indirizzo?: InputMaybe<Scalars['String']['input']>;
  come_arrivare?: InputMaybe<Scalars['String']['input']>;
  come_arrivare_en?: InputMaybe<Scalars['String']['input']>;
  orari?: InputMaybe<Scalars['String']['input']>;
  orari_en?: InputMaybe<Scalars['String']['input']>;
  telefono?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
};

export type NewsMutation = {
  titolo?: InputMaybe<Scalars['String']['input']>;
  data?: InputMaybe<Scalars['String']['input']>;
  categoria?: InputMaybe<Scalars['String']['input']>;
  sintesi?: InputMaybe<Scalars['String']['input']>;
  immagine?: InputMaybe<Scalars['String']['input']>;
  immagine_alt?: InputMaybe<Scalars['String']['input']>;
  pubblicato?: InputMaybe<Scalars['Boolean']['input']>;
  titolo_en?: InputMaybe<Scalars['String']['input']>;
  categoria_en?: InputMaybe<Scalars['String']['input']>;
  sintesi_en?: InputMaybe<Scalars['String']['input']>;
  immagine_alt_en?: InputMaybe<Scalars['String']['input']>;
  corpo_en?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type PagineMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  hero_eyebrow?: InputMaybe<Scalars['String']['input']>;
  hero_titolo?: InputMaybe<Scalars['String']['input']>;
  hero_titolo_accent?: InputMaybe<Scalars['String']['input']>;
  hero_sottotitolo?: InputMaybe<Scalars['String']['input']>;
  hero_immagine?: InputMaybe<Scalars['String']['input']>;
  hero_immagine_alt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type EventiPartsFragment = { __typename: 'Eventi', titolo: string, data: string, categoria: string, descrizione: string, luogo?: string | null, iscrizioniHref?: string | null, pubblicato?: boolean | null, titolo_en?: string | null, descrizione_en?: string | null, luogo_en?: string | null, corpo_en?: string | null, body?: any | null };

export type InfoPartsFragment = { __typename: 'Info', indirizzo: string, come_arrivare: string, come_arrivare_en: string, orari: string, orari_en: string, telefono: string, email: string };

export type NewsPartsFragment = { __typename: 'News', titolo: string, data: string, categoria: string, sintesi: string, immagine: string, immagine_alt: string, pubblicato?: boolean | null, titolo_en?: string | null, categoria_en?: string | null, sintesi_en?: string | null, immagine_alt_en?: string | null, corpo_en?: string | null, body?: any | null };

export type PaginePartsFragment = { __typename: 'Pagine', title: string, description: string, hero_eyebrow?: string | null, hero_titolo?: string | null, hero_titolo_accent?: string | null, hero_sottotitolo?: string | null, hero_immagine?: string | null, hero_immagine_alt?: string | null, body?: any | null };

export type EventiQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventiQuery = { __typename?: 'Query', eventi: { __typename: 'Eventi', id: string, titolo: string, data: string, categoria: string, descrizione: string, luogo?: string | null, iscrizioniHref?: string | null, pubblicato?: boolean | null, titolo_en?: string | null, descrizione_en?: string | null, luogo_en?: string | null, corpo_en?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventiConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventiFilter>;
}>;


export type EventiConnectionQuery = { __typename?: 'Query', eventiConnection: { __typename?: 'EventiConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventiConnectionEdges', cursor: string, node?: { __typename: 'Eventi', id: string, titolo: string, data: string, categoria: string, descrizione: string, luogo?: string | null, iscrizioniHref?: string | null, pubblicato?: boolean | null, titolo_en?: string | null, descrizione_en?: string | null, luogo_en?: string | null, corpo_en?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type InfoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type InfoQuery = { __typename?: 'Query', info: { __typename: 'Info', id: string, indirizzo: string, come_arrivare: string, come_arrivare_en: string, orari: string, orari_en: string, telefono: string, email: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type InfoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<InfoFilter>;
}>;


export type InfoConnectionQuery = { __typename?: 'Query', infoConnection: { __typename?: 'InfoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'InfoConnectionEdges', cursor: string, node?: { __typename: 'Info', id: string, indirizzo: string, come_arrivare: string, come_arrivare_en: string, orari: string, orari_en: string, telefono: string, email: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type NewsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type NewsQuery = { __typename?: 'Query', news: { __typename: 'News', id: string, titolo: string, data: string, categoria: string, sintesi: string, immagine: string, immagine_alt: string, pubblicato?: boolean | null, titolo_en?: string | null, categoria_en?: string | null, sintesi_en?: string | null, immagine_alt_en?: string | null, corpo_en?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type NewsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<NewsFilter>;
}>;


export type NewsConnectionQuery = { __typename?: 'Query', newsConnection: { __typename?: 'NewsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'NewsConnectionEdges', cursor: string, node?: { __typename: 'News', id: string, titolo: string, data: string, categoria: string, sintesi: string, immagine: string, immagine_alt: string, pubblicato?: boolean | null, titolo_en?: string | null, categoria_en?: string | null, sintesi_en?: string | null, immagine_alt_en?: string | null, corpo_en?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PagineQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PagineQuery = { __typename?: 'Query', pagine: { __typename: 'Pagine', id: string, title: string, description: string, hero_eyebrow?: string | null, hero_titolo?: string | null, hero_titolo_accent?: string | null, hero_sottotitolo?: string | null, hero_immagine?: string | null, hero_immagine_alt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PagineConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PagineFilter>;
}>;


export type PagineConnectionQuery = { __typename?: 'Query', pagineConnection: { __typename?: 'PagineConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PagineConnectionEdges', cursor: string, node?: { __typename: 'Pagine', id: string, title: string, description: string, hero_eyebrow?: string | null, hero_titolo?: string | null, hero_titolo_accent?: string | null, hero_sottotitolo?: string | null, hero_immagine?: string | null, hero_immagine_alt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const EventiPartsFragmentDoc = gql`
    fragment EventiParts on Eventi {
  __typename
  titolo
  data
  categoria
  descrizione
  luogo
  iscrizioniHref
  pubblicato
  titolo_en
  descrizione_en
  luogo_en
  corpo_en
  body
}
    `;
export const InfoPartsFragmentDoc = gql`
    fragment InfoParts on Info {
  __typename
  indirizzo
  come_arrivare
  come_arrivare_en
  orari
  orari_en
  telefono
  email
}
    `;
export const NewsPartsFragmentDoc = gql`
    fragment NewsParts on News {
  __typename
  titolo
  data
  categoria
  sintesi
  immagine
  immagine_alt
  pubblicato
  titolo_en
  categoria_en
  sintesi_en
  immagine_alt_en
  corpo_en
  body
}
    `;
export const PaginePartsFragmentDoc = gql`
    fragment PagineParts on Pagine {
  __typename
  title
  description
  hero_eyebrow
  hero_titolo
  hero_titolo_accent
  hero_sottotitolo
  hero_immagine
  hero_immagine_alt
  body
}
    `;
export const EventiDocument = gql`
    query eventi($relativePath: String!) {
  eventi(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventiParts
  }
}
    ${EventiPartsFragmentDoc}`;
export const EventiConnectionDocument = gql`
    query eventiConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventiFilter) {
  eventiConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventiParts
      }
    }
  }
}
    ${EventiPartsFragmentDoc}`;
export const InfoDocument = gql`
    query info($relativePath: String!) {
  info(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...InfoParts
  }
}
    ${InfoPartsFragmentDoc}`;
export const InfoConnectionDocument = gql`
    query infoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: InfoFilter) {
  infoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...InfoParts
      }
    }
  }
}
    ${InfoPartsFragmentDoc}`;
export const NewsDocument = gql`
    query news($relativePath: String!) {
  news(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...NewsParts
  }
}
    ${NewsPartsFragmentDoc}`;
export const NewsConnectionDocument = gql`
    query newsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: NewsFilter) {
  newsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...NewsParts
      }
    }
  }
}
    ${NewsPartsFragmentDoc}`;
export const PagineDocument = gql`
    query pagine($relativePath: String!) {
  pagine(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PagineParts
  }
}
    ${PaginePartsFragmentDoc}`;
export const PagineConnectionDocument = gql`
    query pagineConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PagineFilter) {
  pagineConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PagineParts
      }
    }
  }
}
    ${PaginePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      eventi(variables: EventiQueryVariables, options?: C): Promise<{data: EventiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventiQueryVariables, query: string}> {
        return requester<{data: EventiQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventiQueryVariables, query: string}, EventiQueryVariables>(EventiDocument, variables, options);
      },
    eventiConnection(variables?: EventiConnectionQueryVariables, options?: C): Promise<{data: EventiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventiConnectionQueryVariables, query: string}> {
        return requester<{data: EventiConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventiConnectionQueryVariables, query: string}, EventiConnectionQueryVariables>(EventiConnectionDocument, variables, options);
      },
    info(variables: InfoQueryVariables, options?: C): Promise<{data: InfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InfoQueryVariables, query: string}> {
        return requester<{data: InfoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InfoQueryVariables, query: string}, InfoQueryVariables>(InfoDocument, variables, options);
      },
    infoConnection(variables?: InfoConnectionQueryVariables, options?: C): Promise<{data: InfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InfoConnectionQueryVariables, query: string}> {
        return requester<{data: InfoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: InfoConnectionQueryVariables, query: string}, InfoConnectionQueryVariables>(InfoConnectionDocument, variables, options);
      },
    news(variables: NewsQueryVariables, options?: C): Promise<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}> {
        return requester<{data: NewsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsQueryVariables, query: string}, NewsQueryVariables>(NewsDocument, variables, options);
      },
    newsConnection(variables?: NewsConnectionQueryVariables, options?: C): Promise<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}> {
        return requester<{data: NewsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: NewsConnectionQueryVariables, query: string}, NewsConnectionQueryVariables>(NewsConnectionDocument, variables, options);
      },
    pagine(variables: PagineQueryVariables, options?: C): Promise<{data: PagineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagineQueryVariables, query: string}> {
        return requester<{data: PagineQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagineQueryVariables, query: string}, PagineQueryVariables>(PagineDocument, variables, options);
      },
    pagineConnection(variables?: PagineConnectionQueryVariables, options?: C): Promise<{data: PagineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagineConnectionQueryVariables, query: string}> {
        return requester<{data: PagineConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PagineConnectionQueryVariables, query: string}, PagineConnectionQueryVariables>(PagineConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  