import { defineConfig } from 'tinacms';

// Credenziali TinaCloud — aggiungile come variabili d'ambiente:
//   TINA_CLIENT_ID  →  Vercel: Project Settings > Environment Variables
//   TINA_TOKEN      →  stessa posizione
// Ottienile su: https://app.tina.io

export default defineConfig({
  branch: process.env.VERCEL_GIT_COMMIT_REF || process.env.GITHUB_BRANCH || process.env.HEAD || 'main',
  clientId: process.env.TINA_CLIENT_ID || '',
  token: process.env.TINA_TOKEN || '',

  build: {
    outputFolder: 'admin',
    publicFolder: 'public',
  },

  media: {
    tina: {
      // Le immagini del sito vivono direttamente in public/ (root)
      mediaRoot: '',
      publicFolder: 'public',
    },
  },

  schema: {
    collections: [
      // ─── EVENTI ────────────────────────────────────────────────────────────
      // Il marketing può aggiungere eventi da qui: https://app.tina.io
      // Ogni evento è un file .md in src/content/eventi/
      // ───────────────────────────────────────────────────────────────────────
      {
        name: 'eventi',
        label: 'Eventi',
        path: 'src/content/eventi',
        format: 'md',
        fields: [
          {
            type: 'string',
            name: 'titolo',
            label: 'Titolo evento',
            isTitle: true,
            required: true,
          },
          {
            type: 'datetime',
            name: 'data',
            label: 'Data',
            required: true,
            ui: { dateFormat: 'DD/MM/YYYY' },
          },
          {
            type: 'string',
            name: 'categoria',
            label: 'Categoria',
            required: true,
            options: ['Torneo', 'Clinic', 'Evento', 'Camp'],
          },
          {
            type: 'string',
            name: 'descrizione',
            label: 'Descrizione breve',
            required: true,
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'luogo',
            label: 'Luogo (es. Campo 3, Club House)',
          },
          {
            type: 'string',
            name: 'iscrizioniHref',
            label: 'Link iscrizioni (URL)',
          },
          {
            type: 'boolean',
            name: 'pubblicato',
            label: 'Pubblicato',
          },
          {
            type: 'string',
            name: 'titolo_en',
            label: '🇬🇧 Titolo (inglese)',
          },
          {
            type: 'string',
            name: 'descrizione_en',
            label: '🇬🇧 Descrizione breve (inglese)',
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'luogo_en',
            label: '🇬🇧 Luogo (inglese)',
          },
          {
            type: 'string',
            name: 'corpo_en',
            label: '🇬🇧 Dettagli evento (inglese)',
            ui: { component: 'textarea' },
          },
          {
            type: 'rich-text',
            name: 'body',
            label: 'Dettagli evento (italiano)',
            isBody: true,
          },
        ],
      },
      // ─── SERVIZI CLUB LIFE ─────────────────────────────────────────────────
      // Card della sezione "Servizi e Partner" di Club Life.
      // Ogni servizio è un file .md in src/content/servizi/
      // ───────────────────────────────────────────────────────────────────────
      {
        name: 'servizi',
        label: 'Servizi Club Life',
        path: 'src/content/servizi',
        format: 'md',
        fields: [
          {
            type: 'string',
            name: 'titolo',
            label: 'Titolo',
            isTitle: true,
            required: true,
          },
          {
            type: 'number',
            name: 'ordine',
            label: 'Ordine nella griglia (1 = primo)',
            required: true,
          },
          {
            type: 'string',
            name: 'icon',
            label: 'Icona',
            required: true,
            options: [
              { value: 'coach', label: 'Preparatore (persona)' },
              { value: 'ballmachine', label: 'Macchina lanciapalline' },
              { value: 'birthday', label: 'Compleanno (torta)' },
              { value: 'locker', label: 'Armadietti' },
              { value: 'shop', label: 'Shop (borsa)' },
              { value: 'medical', label: 'Medico (scudo con croce)' },
              { value: 'graduation', label: 'Studio (tocco di laurea)' },
              { value: 'briefcase', label: 'Corporate (valigetta)' },
            ],
          },
          {
            type: 'string',
            name: 'desc',
            label: 'Descrizione breve (nella card)',
            required: true,
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'dettaglio',
            label: 'Dettaglio (nel popup) — grassetto con **doppi asterischi**',
            required: true,
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'href',
            label: 'Link di approfondimento (opzionale, es. /personal-trainer)',
          },
          {
            type: 'string',
            name: 'titolo_en',
            label: '🇬🇧 Titolo (inglese)',
          },
          {
            type: 'string',
            name: 'desc_en',
            label: '🇬🇧 Descrizione breve (inglese)',
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'dettaglio_en',
            label: '🇬🇧 Dettaglio (inglese)',
            ui: { component: 'textarea' },
          },
        ],
      },
      // ─── PLANNING CORSI ────────────────────────────────────────────────────
      // Planning settimanale dei corsi di gruppo (pagina Preparazione
      // Atletica). File unico: ogni riga è una lezione.
      // ───────────────────────────────────────────────────────────────────────
      {
        name: 'planning',
        label: 'Planning Corsi',
        path: 'src/content/planning',
        format: 'md',
        ui: {
          allowedActions: { create: false, delete: false },
        },
        fields: [
          {
            type: 'object',
            name: 'lezioni',
            label: 'Lezioni',
            list: true,
            ui: {
              itemProps: (item: Record<string, string>) => ({
                label: item?.giorno && item?.ora
                  ? `${(item.giorno || '').toUpperCase()} ${item.ora} — ${item.nome || ''}`
                  : 'Nuova lezione',
              }),
            },
            fields: [
              {
                type: 'string',
                name: 'giorno',
                label: 'Giorno',
                required: true,
                options: [
                  { value: 'lun', label: 'Lunedì' },
                  { value: 'mar', label: 'Martedì' },
                  { value: 'mer', label: 'Mercoledì' },
                  { value: 'gio', label: 'Giovedì' },
                  { value: 'ven', label: 'Venerdì' },
                  { value: 'sab', label: 'Sabato' },
                  { value: 'dom', label: 'Domenica' },
                ],
              },
              {
                type: 'string',
                name: 'ora',
                label: 'Orario (es. 09:15)',
                required: true,
              },
              {
                type: 'string',
                name: 'categoria',
                label: 'Categoria',
                required: true,
                options: [
                  { value: 'S', label: 'Strength' },
                  { value: 'B', label: 'Balance' },
                  { value: 'E', label: 'Endurance' },
                ],
              },
              {
                type: 'string',
                name: 'nome',
                label: 'Nome corso',
                required: true,
              },
            ],
          },
        ],
      },
      // ─── MEMBERSHIP (tabella prezzi) ────────────────────────────────────────
      // Tabella abbonamenti Silver/Gold/Platinum, condivisa da tennis,
      // preparazione-atletica e personal-trainer.
      // ───────────────────────────────────────────────────────────────────────
      {
        name: 'membership',
        label: 'Tabella Membership',
        path: 'src/content/membership',
        format: 'md',
        ui: {
          allowedActions: { create: false, delete: false },
        },
        fields: [
          { type: 'string', name: 'titolo', label: 'Titolo (prima parte)', required: true },
          { type: 'string', name: 'titolo_accent', label: 'Titolo (parte evidenziata in rosso)', required: true },
          { type: 'string', name: 'sottotitolo', label: 'Sottotitolo', required: true, ui: { component: 'textarea' } },
          { type: 'string', name: 'silver_nome', label: 'Nome livello 1 (es. "Silver")', required: true },
          { type: 'string', name: 'gold_nome', label: 'Nome livello 2 (es. "Gold")', required: true },
          { type: 'string', name: 'platinum_nome', label: 'Nome livello 3 (es. "Platinum")', required: true },
          { type: 'string', name: 'platinum_badge', label: 'Badge sul livello 3 (es. "Più completo")', required: true },
          { type: 'string', name: 'cta_label', label: 'Testo pulsante (in ogni colonna)', required: true },
          {
            type: 'object',
            name: 'categorie',
            label: 'Categorie e righe della tabella',
            list: true,
            required: true,
            ui: {
              itemProps: (item: Record<string, string>) => ({ label: item?.label || 'Nuova categoria' }),
            },
            fields: [
              { type: 'string', name: 'label', label: 'Nome categoria (es. "Accesso ai campi")', required: true },
              { type: 'string', name: 'label_en', label: '🇬🇧 Nome categoria (inglese)' },
              {
                type: 'object',
                name: 'righe',
                label: 'Righe',
                list: true,
                required: true,
                ui: {
                  itemProps: (item: Record<string, string>) => ({ label: item?.feature || 'Nuova riga' }),
                },
                fields: [
                  { type: 'string', name: 'feature', label: 'Nome caratteristica', required: true },
                  { type: 'string', name: 'feature_tooltip', label: 'Tooltip (opzionale, icona info)' },
                  {
                    type: 'string', name: 'silver_tipo', label: 'Livello 1 — tipo cella', required: true,
                    options: [
                      { value: 'incluso', label: 'Incluso (verde)' },
                      { value: 'parziale', label: 'Parziale/sconto (ambra)' },
                      { value: 'valore', label: 'Valore testuale (es. "4 giorni")' },
                      { value: 'check', label: 'Solo icona di spunta' },
                    ],
                  },
                  { type: 'string', name: 'silver_valore', label: 'Livello 1 — testo cella (non serve per "check")' },
                  {
                    type: 'string', name: 'gold_tipo', label: 'Livello 2 — tipo cella', required: true,
                    options: [
                      { value: 'incluso', label: 'Incluso (verde)' },
                      { value: 'parziale', label: 'Parziale/sconto (ambra)' },
                      { value: 'valore', label: 'Valore testuale' },
                      { value: 'check', label: 'Solo icona di spunta' },
                    ],
                  },
                  { type: 'string', name: 'gold_valore', label: 'Livello 2 — testo cella (non serve per "check")' },
                  {
                    type: 'string', name: 'platinum_tipo', label: 'Livello 3 — tipo cella', required: true,
                    options: [
                      { value: 'incluso', label: 'Incluso (verde)' },
                      { value: 'parziale', label: 'Parziale/sconto (ambra)' },
                      { value: 'valore', label: 'Valore testuale' },
                      { value: 'check', label: 'Solo icona di spunta' },
                    ],
                  },
                  { type: 'string', name: 'platinum_valore', label: 'Livello 3 — testo cella (non serve per "check")' },
                  { type: 'string', name: 'feature_en', label: '🇬🇧 Nome caratteristica (inglese)' },
                  { type: 'string', name: 'feature_tooltip_en', label: '🇬🇧 Tooltip (inglese)' },
                  { type: 'string', name: 'silver_valore_en', label: '🇬🇧 Livello 1 — testo cella (inglese)' },
                  { type: 'string', name: 'gold_valore_en', label: '🇬🇧 Livello 2 — testo cella (inglese)' },
                  { type: 'string', name: 'platinum_valore_en', label: '🇬🇧 Livello 3 — testo cella (inglese)' },
                ],
              },
            ],
          },
          { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
          { type: 'string', name: 'titolo_accent_en', label: '🇬🇧 Titolo evidenziato (inglese)' },
          { type: 'string', name: 'sottotitolo_en', label: '🇬🇧 Sottotitolo (inglese)', ui: { component: 'textarea' } },
          { type: 'string', name: 'platinum_badge_en', label: '🇬🇧 Badge livello 3 (inglese)' },
          { type: 'string', name: 'cta_label_en', label: '🇬🇧 Testo pulsante (inglese)' },
        ],
      },
      // ─── INFO CLUB ─────────────────────────────────────────────────────────
      // File unico con orari, indirizzo e contatti del Club.
      // Le modifiche si riflettono su tutte le pagine (sezione "Vieni a trovarci").
      // ───────────────────────────────────────────────────────────────────────
      {
        name: 'info',
        label: 'Informazioni Club',
        path: 'src/content/info',
        format: 'md',
        ui: {
          allowedActions: { create: false, delete: false },
        },
        fields: [
          {
            type: 'string',
            name: 'indirizzo',
            label: 'Indirizzo',
            required: true,
          },
          {
            type: 'string',
            name: 'come_arrivare',
            label: 'Come arrivare',
            required: true,
          },
          {
            type: 'string',
            name: 'come_arrivare_en',
            label: '🇬🇧 Come arrivare (inglese)',
            required: true,
          },
          {
            type: 'string',
            name: 'orari',
            label: 'Orari Club (una riga per fascia)',
            required: true,
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'orari_en',
            label: '🇬🇧 Orari Club (inglese)',
            required: true,
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'telefono',
            label: 'Telefono',
            required: true,
          },
          {
            type: 'string',
            name: 'email',
            label: 'Email',
            required: true,
          },
        ],
      },
      // ─── DOCUMENTI LEGALI ──────────────────────────────────────────────────
      // File unico con i PDF legali linkati dal footer (sezione "Legal").
      // Per sostituire un documento basta caricare un nuovo PDF sul campo:
      // il file va in public/legal/ e il link nel footer si aggiorna da solo.
      // ─────────────────────────────────────────────────────────────────────
      {
        name: 'legal',
        label: 'Documenti Legali',
        path: 'src/content/legal',
        format: 'md',
        ui: {
          allowedActions: { create: false, delete: false },
        },
        fields: [
          {
            type: 'image',
            name: 'codice_condotta',
            label: 'Codice di Condotta (PDF)',
          },
          {
            type: 'image',
            name: 'nomina_responsabile',
            label: 'Nomina Responsabile Safeguarding (PDF)',
          },
        ],
      },
      // ─── HELP DESK ─────────────────────────────────────────────────────────
      // Guide della knowledge base Club Life (sezione Help Desk).
      // Ogni guida è un file .md in src/content/helpdesk/
      // ───────────────────────────────────────────────────────────────────────
      {
        name: 'helpdesk',
        label: 'Help Desk',
        path: 'src/content/helpdesk',
        format: 'md',
        fields: [
          {
            type: 'string',
            name: 'titolo',
            label: 'Titolo',
            isTitle: true,
            required: true,
          },
          {
            type: 'string',
            name: 'categoria',
            label: 'Categoria',
            required: true,
            options: [
              { value: 'iscrizioni', label: 'Iscrizioni & Tesseramento' },
              { value: 'prenotazioni', label: 'Prenotazioni' },
              { value: 'app', label: 'App & Area Riservata' },
              { value: 'pagamenti', label: 'Pagamenti & Ricevute' },
              { value: 'regolamento', label: 'Regolamento' },
              { value: 'scuola', label: 'Scuola Tennis' },
            ],
          },
          {
            type: 'string',
            name: 'sintesi',
            label: 'Sintesi (anteprima nella card)',
            required: true,
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'tags',
            label: 'Tag (per la ricerca)',
            list: true,
          },
          {
            type: 'datetime',
            name: 'aggiornato',
            label: 'Ultimo aggiornamento',
            required: true,
            ui: { dateFormat: 'DD/MM/YYYY' },
          },
          {
            type: 'string',
            name: 'titolo_en',
            label: '🇬🇧 Titolo (inglese)',
          },
          {
            type: 'string',
            name: 'sintesi_en',
            label: '🇬🇧 Sintesi (inglese)',
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'tags_en',
            label: '🇬🇧 Tag (inglese)',
            list: true,
          },
          {
            type: 'string',
            name: 'corpo_en',
            label: '🇬🇧 Testo guida (inglese) — un paragrafo per riga vuota, grassetto con **doppi asterischi**',
            ui: { component: 'textarea' },
          },
          {
            type: 'rich-text',
            name: 'body',
            label: 'Testo guida (italiano)',
            isBody: true,
          },
        ],
      },
      // ─── NEWS CLUB LIFE ────────────────────────────────────────────────────
      // Articoli della bacheca Club Life (carosello "News dal Club").
      // Ogni news è un file .md in src/content/news/
      // ───────────────────────────────────────────────────────────────────────
      {
        name: 'news',
        label: 'News Club Life',
        path: 'src/content/news',
        format: 'md',
        fields: [
          {
            type: 'string',
            name: 'titolo',
            label: 'Titolo',
            isTitle: true,
            required: true,
          },
          {
            type: 'datetime',
            name: 'data',
            label: 'Data',
            required: true,
            ui: { dateFormat: 'DD/MM/YYYY' },
          },
          {
            type: 'string',
            name: 'categoria',
            label: 'Categoria (es. Corsi, Scuola Tennis)',
            required: true,
          },
          {
            type: 'string',
            name: 'sintesi',
            label: 'Sintesi (anteprima nella card)',
            required: true,
            ui: { component: 'textarea' },
          },
          {
            type: 'image',
            name: 'immagine',
            label: 'Immagine',
            required: true,
          },
          {
            type: 'string',
            name: 'immagine_alt',
            label: 'Testo alternativo immagine',
            required: true,
          },
          {
            type: 'boolean',
            name: 'pubblicato',
            label: 'Pubblicato',
          },
          {
            type: 'string',
            name: 'cta_label',
            label: 'Pulsante — testo (es. Iscriviti ora)',
          },
          {
            type: 'string',
            name: 'cta_href',
            label: 'Pulsante — link (URL esterno o percorso interno, es. /contatti). Il pulsante appare solo se compilato.',
          },
          {
            type: 'string',
            name: 'titolo_en',
            label: '🇬🇧 Titolo (inglese)',
          },
          {
            type: 'string',
            name: 'categoria_en',
            label: '🇬🇧 Categoria (inglese)',
          },
          {
            type: 'string',
            name: 'cta_label_en',
            label: '🇬🇧 Pulsante — testo (inglese)',
          },
          {
            type: 'string',
            name: 'sintesi_en',
            label: '🇬🇧 Sintesi (inglese)',
            ui: { component: 'textarea' },
          },
          {
            type: 'string',
            name: 'immagine_alt_en',
            label: '🇬🇧 Testo alternativo immagine (inglese)',
          },
          {
            type: 'string',
            name: 'corpo_en',
            label: '🇬🇧 Testo articolo (inglese) — un paragrafo per riga vuota',
            ui: { component: 'textarea' },
          },
          {
            type: 'rich-text',
            name: 'body',
            label: 'Testo articolo (italiano)',
            isBody: true,
          },
        ],
      },
      // ─── PAGINE ──────────────────────────────────────────────────────────────
      // Una voce unica "Pagine" con un template per pagina: cliccandola si apre
      // l'elenco di tutte le pagine del sito, ognuna con SEO + hero (comuni a
      // tutte) più i propri campi di corpo pagina, dove presenti.
      // ───────────────────────────────────────────────────────────────────────
      (() => {
        // Campi comuni a ogni pagina (SEO + hero): riusati in ogni template.
        const heroSeoFields = [
          { type: 'string', name: 'title', label: 'Titolo SEO', isTitle: true, required: true },
          { type: 'string', name: 'description', label: 'Descrizione SEO', required: true, ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_eyebrow', label: 'Hero — eyebrow' },
          { type: 'string', name: 'hero_titolo', label: 'Hero — titolo' },
          { type: 'string', name: 'hero_titolo_accent', label: 'Hero — titolo (parte evidenziata in rosso)' },
          { type: 'string', name: 'hero_sottotitolo', label: 'Hero — sottotitolo', ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_immagine', label: 'Hero — percorso immagine (es. /nome-file.avif in public/)' },
          { type: 'string', name: 'hero_immagine_alt', label: 'Hero — testo alternativo immagine' },
          { type: 'string', name: 'title_en', label: '🇬🇧 Titolo SEO (inglese)' },
          { type: 'string', name: 'description_en', label: '🇬🇧 Descrizione SEO (inglese)', ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_eyebrow_en', label: '🇬🇧 Hero — eyebrow (inglese)' },
          { type: 'string', name: 'hero_titolo_en', label: '🇬🇧 Hero — titolo (inglese)' },
          { type: 'string', name: 'hero_titolo_accent_en', label: '🇬🇧 Hero — titolo evidenziato (inglese)' },
          { type: 'string', name: 'hero_sottotitolo_en', label: '🇬🇧 Hero — sottotitolo (inglese)', ui: { component: 'textarea' } },
          { type: 'string', name: 'hero_immagine_alt_en', label: '🇬🇧 Hero — testo alternativo immagine (inglese)' },
        ];

        return {
          name: 'pagine',
          label: 'Pagine',
          path: 'src/content/pagine',
          format: 'md',
          templates: [
            {
              name: 'generica',
              label: 'Pagina generica (solo SEO + Hero)',
              fields: [...heroSeoFields],
            },
            {
              name: 'storia',
              label: 'Storia',
              fields: [
                ...heroSeoFields,
                { type: 'string', name: 'storia_sezione1_eyebrow', label: 'Sezione 1 — eyebrow (es. "La timeline")', required: true },
                { type: 'string', name: 'storia_sezione1_titolo', label: 'Sezione 1 — titolo', required: true },
                { type: 'string', name: 'storia_sezione1_titolo_accent', label: 'Sezione 1 — titolo (parte evidenziata in rosso)', required: true },
                {
                  type: 'object', name: 'storia_timeline', label: 'Timeline', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.anno ? `${item.anno} — ${item.testo || ''}` : 'Nuova voce' }) },
                  fields: [
                    { type: 'string', name: 'anno', label: 'Anno', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'storia_sezione2_eyebrow', label: 'Sezione 2 — eyebrow (es. "Il club oggi")', required: true },
                { type: 'string', name: 'storia_sezione2_titolo', label: 'Sezione 2 — titolo', required: true },
                { type: 'string', name: 'storia_sezione2_titolo_accent', label: 'Sezione 2 — titolo (parte evidenziata in rosso)', required: true },
                { type: 'string', name: 'storia_paragrafo1', label: 'Paragrafo 1 — grassetto con **doppi asterischi**', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'storia_paragrafo2', label: 'Paragrafo 2 — grassetto con **doppi asterischi**', required: true, ui: { component: 'textarea' } },
                {
                  type: 'object', name: 'storia_galleria', label: 'Galleria immagini', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.alt || 'Immagine' }) },
                  fields: [
                    { type: 'image', name: 'immagine', label: 'Immagine', required: true },
                    { type: 'string', name: 'alt', label: 'Testo alternativo', required: true },
                  ],
                },
                { type: 'string', name: 'storia_sezione1_eyebrow_en', label: '🇬🇧 Sezione 1 — eyebrow (inglese)' },
                { type: 'string', name: 'storia_sezione1_titolo_en', label: '🇬🇧 Sezione 1 — titolo (inglese)' },
                { type: 'string', name: 'storia_sezione1_titolo_accent_en', label: '🇬🇧 Sezione 1 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'storia_sezione2_eyebrow_en', label: '🇬🇧 Sezione 2 — eyebrow (inglese)' },
                { type: 'string', name: 'storia_sezione2_titolo_en', label: '🇬🇧 Sezione 2 — titolo (inglese)' },
                { type: 'string', name: 'storia_sezione2_titolo_accent_en', label: '🇬🇧 Sezione 2 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'storia_paragrafo1_en', label: '🇬🇧 Paragrafo 1 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'storia_paragrafo2_en', label: '🇬🇧 Paragrafo 2 (inglese)', ui: { component: 'textarea' } },
              ],
            },
            {
              name: 'summer_camps',
              label: 'Summer Camps',
              fields: [
                ...heroSeoFields,
                { type: 'string', name: 'camps_sezione1_eyebrow', label: 'Sezione 1 — eyebrow', required: true },
                { type: 'string', name: 'camps_sezione1_titolo', label: 'Sezione 1 — titolo', required: true },
                { type: 'string', name: 'camps_sezione1_titolo_accent', label: 'Sezione 1 — titolo evidenziato', required: true },
                {
                  type: 'object', name: 'camps_features', label: 'Caratteristiche del programma', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.titolo || 'Nuova caratteristica' }) },
                  fields: [
                    { type: 'string', name: 'titolo', label: 'Titolo', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'image', name: 'camps_immagine1', label: 'Immagine 1 (grande)', required: true },
                { type: 'string', name: 'camps_immagine1_alt', label: 'Immagine 1 — testo alternativo', required: true },
                { type: 'image', name: 'camps_immagine2', label: 'Immagine 2 (piccola)', required: true },
                { type: 'string', name: 'camps_immagine2_alt', label: 'Immagine 2 — testo alternativo', required: true },
                { type: 'string', name: 'camps_sezione2_eyebrow', label: 'Sezione 2 — eyebrow', required: true },
                { type: 'string', name: 'camps_sezione2_titolo', label: 'Sezione 2 — titolo', required: true },
                { type: 'string', name: 'camps_sezione2_titolo_accent', label: 'Sezione 2 — titolo evidenziato', required: true },
                {
                  type: 'object', name: 'camps_info_rapide', label: 'Info rapide (Quando, Orari, Età...)', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.label || 'Nuova info' }) },
                  fields: [
                    { type: 'string', name: 'label', label: 'Etichetta (es. "Quando")', required: true },
                    { type: 'string', name: 'valore', label: 'Valore', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'label_en', label: '🇬🇧 Etichetta (inglese)' },
                    { type: 'string', name: 'valore_en', label: '🇬🇧 Valore (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'camps_giornata_eyebrow', label: 'Giornata tipo — eyebrow', required: true },
                { type: 'string', name: 'camps_giornata_titolo', label: 'Giornata tipo — titolo', required: true },
                {
                  type: 'object', name: 'camps_giornata', label: 'Giornata tipo — fasce orarie', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.orario ? `${item.orario} — ${item.titolo || ''}` : 'Nuova fascia oraria' }) },
                  fields: [
                    { type: 'string', name: 'orario', label: 'Orario (es. "8.30 – 9.00")', required: true },
                    { type: 'string', name: 'titolo', label: 'Titolo', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'camps_settimanale_eyebrow', label: 'Programma settimanale — eyebrow', required: true },
                { type: 'string', name: 'camps_settimanale_titolo', label: 'Programma settimanale — titolo', required: true },
                {
                  type: 'object', name: 'camps_settimanale', label: 'Programma tecnico settimanale', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.giorno ? `${item.giorno} — ${item.colpo || ''}` : 'Nuovo giorno' }) },
                  fields: [
                    { type: 'string', name: 'giorno', label: 'Giorno (es. "Lunedì")', required: true },
                    { type: 'string', name: 'colpo', label: 'Colpo (es. "Dritto")', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'giorno_en', label: '🇬🇧 Giorno (inglese)' },
                    { type: 'string', name: 'colpo_en', label: '🇬🇧 Colpo (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'camps_cosa_portare_titolo', label: 'Cosa portare — titolo', required: true },
                { type: 'string', name: 'camps_cosa_portare', label: 'Cosa portare — elenco', list: true, required: true },
                { type: 'string', name: 'camps_obbligatorio', label: 'Nota obbligatoria (es. certificato medico)', required: true },
                { type: 'string', name: 'camps_kit_benvenuto', label: 'Kit di benvenuto', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'camps_quote_eyebrow', label: 'Quote — eyebrow', required: true },
                { type: 'string', name: 'camps_quote_titolo', label: 'Quote — titolo', required: true },
                {
                  type: 'object', name: 'camps_quote_righe', label: 'Tabella quote', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.categoria || 'Nuova riga' }) },
                  fields: [
                    { type: 'string', name: 'categoria', label: 'Categoria (es. "Soci")', required: true },
                    { type: 'string', name: 'prezzo_settimana', label: 'Prezzo a settimana', required: true },
                    { type: 'string', name: 'prezzo_dal2', label: 'Prezzo dalla 2ª settimana', required: true },
                    { type: 'string', name: 'prezzo_fratelli', label: 'Prezzo fratelli', required: true },
                    { type: 'string', name: 'categoria_en', label: '🇬🇧 Categoria (inglese)' },
                  ],
                },
                { type: 'string', name: 'camps_quote_note', label: 'Note quote/condizioni', list: true, required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'camps_cta_label', label: 'Etichetta bottone iscrizione', required: true },
                { type: 'string', name: 'camps_sezione1_eyebrow_en', label: '🇬🇧 Sezione 1 — eyebrow (inglese)' },
                { type: 'string', name: 'camps_sezione1_titolo_en', label: '🇬🇧 Sezione 1 — titolo (inglese)' },
                { type: 'string', name: 'camps_sezione1_titolo_accent_en', label: '🇬🇧 Sezione 1 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'camps_immagine1_alt_en', label: '🇬🇧 Immagine 1 — alt (inglese)' },
                { type: 'string', name: 'camps_immagine2_alt_en', label: '🇬🇧 Immagine 2 — alt (inglese)' },
                { type: 'string', name: 'camps_sezione2_eyebrow_en', label: '🇬🇧 Sezione 2 — eyebrow (inglese)' },
                { type: 'string', name: 'camps_sezione2_titolo_en', label: '🇬🇧 Sezione 2 — titolo (inglese)' },
                { type: 'string', name: 'camps_sezione2_titolo_accent_en', label: '🇬🇧 Sezione 2 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'camps_giornata_eyebrow_en', label: '🇬🇧 Giornata tipo — eyebrow (inglese)' },
                { type: 'string', name: 'camps_giornata_titolo_en', label: '🇬🇧 Giornata tipo — titolo (inglese)' },
                { type: 'string', name: 'camps_settimanale_eyebrow_en', label: '🇬🇧 Programma settimanale — eyebrow (inglese)' },
                { type: 'string', name: 'camps_settimanale_titolo_en', label: '🇬🇧 Programma settimanale — titolo (inglese)' },
                { type: 'string', name: 'camps_cosa_portare_titolo_en', label: '🇬🇧 Cosa portare — titolo (inglese)' },
                { type: 'string', name: 'camps_cosa_portare_en', label: '🇬🇧 Cosa portare — elenco (inglese)', list: true },
                { type: 'string', name: 'camps_obbligatorio_en', label: '🇬🇧 Nota obbligatoria (inglese)' },
                { type: 'string', name: 'camps_kit_benvenuto_en', label: '🇬🇧 Kit di benvenuto (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'camps_quote_eyebrow_en', label: '🇬🇧 Quote — eyebrow (inglese)' },
                { type: 'string', name: 'camps_quote_titolo_en', label: '🇬🇧 Quote — titolo (inglese)' },
                { type: 'string', name: 'camps_quote_note_en', label: '🇬🇧 Note quote/condizioni (inglese)', list: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'camps_cta_label_en', label: '🇬🇧 Etichetta bottone iscrizione (inglese)' },
              ],
            },
            {
              name: 'scuola_tennis',
              label: 'Scuola Tennis',
              fields: [
                ...heroSeoFields,
                { type: 'string', name: 'scuola_sezione1_eyebrow', label: 'Sezione 1 — eyebrow', required: true },
                { type: 'string', name: 'scuola_sezione1_titolo', label: 'Sezione 1 — titolo', required: true },
                { type: 'string', name: 'scuola_sezione1_titolo_accent', label: 'Sezione 1 — titolo evidenziato', required: true },
                { type: 'string', name: 'scuola_sezione1_lead', label: 'Sezione 1 — testo introduttivo', required: true, ui: { component: 'textarea' } },
                {
                  type: 'object', name: 'scuola_livelli', label: 'Livelli (percorso a colori)', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.nome || 'Nuovo livello' }) },
                  fields: [
                    {
                      type: 'string', name: 'dot', label: 'Colore', required: true,
                      options: [
                        { value: 'rosso', label: 'Rosso' },
                        { value: 'arancio', label: 'Arancio' },
                        { value: 'verde', label: 'Verde' },
                        { value: 'giallo', label: 'Giallo' },
                      ],
                    },
                    { type: 'string', name: 'nome', label: 'Nome livello', required: true },
                    { type: 'string', name: 'tag', label: 'Tag (es. "Mini Tennis")', required: true },
                    { type: 'string', name: 'range', label: 'Fascia età', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'nome_en', label: '🇬🇧 Nome (inglese)' },
                    { type: 'string', name: 'tag_en', label: '🇬🇧 Tag (inglese)' },
                    { type: 'string', name: 'range_en', label: '🇬🇧 Fascia età (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'scuola_livelli_footer_testo', label: 'Testo dopo i livelli (prima del link)', required: true },
                { type: 'string', name: 'scuola_livelli_footer_link_label', label: 'Etichetta link (verso /agonistica)', required: true },
                { type: 'string', name: 'scuola_sezione2_eyebrow', label: 'Sezione 2 — eyebrow', required: true },
                { type: 'string', name: 'scuola_sezione2_titolo', label: 'Sezione 2 — titolo', required: true },
                { type: 'string', name: 'scuola_sezione2_titolo_accent', label: 'Sezione 2 — titolo evidenziato', required: true },
                {
                  type: 'object', name: 'scuola_iscrizione_cards', label: 'Card iscrizione', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.titolo || 'Nuova card' }) },
                  fields: [
                    { type: 'string', name: 'titolo', label: 'Titolo', required: true },
                    { type: 'string', name: 'tag', label: 'Tag (es. "Nati nel 2020 e 2021")', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
                    { type: 'string', name: 'tag_en', label: '🇬🇧 Tag (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'scuola_iscrizione_cta_label', label: 'Testo pulsante iscrizione', required: true },
                { type: 'string', name: 'scuola_sezione3_eyebrow', label: 'Sezione 3 — eyebrow', required: true },
                { type: 'string', name: 'scuola_sezione3_titolo', label: 'Sezione 3 — titolo', required: true },
                { type: 'string', name: 'scuola_sezione3_titolo_accent', label: 'Sezione 3 — titolo evidenziato', required: true },
                { type: 'string', name: 'scuola_sezione3_badge', label: 'Sezione 3 — badge (es. "Vavassori Tennis Academy...")', required: true },
                { type: 'string', name: 'scuola_sezione3_paragrafo1', label: 'Sezione 3 — paragrafo 1 (**grassetto**)', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione3_paragrafo2', label: 'Sezione 3 — paragrafo 2', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione3_paragrafo3', label: 'Sezione 3 — paragrafo 3 (**grassetto**)', required: true, ui: { component: 'textarea' } },
                { type: 'image', name: 'scuola_sezione3_immagine', label: 'Sezione 3 — immagine', required: true },
                { type: 'string', name: 'scuola_sezione3_immagine_alt', label: 'Sezione 3 — immagine, testo alternativo', required: true },
                { type: 'string', name: 'scuola_sezione4_eyebrow', label: 'Sezione 4 — eyebrow', required: true },
                { type: 'string', name: 'scuola_sezione4_titolo', label: 'Sezione 4 — titolo', required: true },
                { type: 'string', name: 'scuola_sezione4_titolo_accent', label: 'Sezione 4 — titolo evidenziato', required: true },
                {
                  type: 'object', name: 'scuola_tornei', label: "Tornei durante l'anno", list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.nome || 'Nuovo torneo' }) },
                  fields: [
                    { type: 'string', name: 'quando', label: 'Quando (es. "Dicembre")', required: true },
                    { type: 'string', name: 'nome', label: 'Nome torneo', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'quando_en', label: '🇬🇧 Quando (inglese)' },
                    { type: 'string', name: 'nome_en', label: '🇬🇧 Nome (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'scuola_sezione4_footer_testo', label: 'Testo finale (FITP Junior Program, **grassetto**)', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione5_eyebrow', label: 'Sezione 5 (Scuola Tennis Estiva) — eyebrow', required: true },
                { type: 'string', name: 'scuola_sezione5_titolo', label: 'Sezione 5 — titolo', required: true },
                { type: 'string', name: 'scuola_sezione5_titolo_accent', label: 'Sezione 5 — titolo evidenziato', required: true },
                { type: 'string', name: 'scuola_sezione5_testo', label: 'Sezione 5 — testo introduttivo', required: true, ui: { component: 'textarea' } },
                {
                  type: 'object', name: 'scuola_sezione5_info_rapide', label: 'Sezione 5 — info rapide', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.label || 'Nuova info' }) },
                  fields: [
                    { type: 'string', name: 'label', label: 'Etichetta', required: true },
                    { type: 'string', name: 'valore', label: 'Valore', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'label_en', label: '🇬🇧 Etichetta (inglese)' },
                    { type: 'string', name: 'valore_en', label: '🇬🇧 Valore (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                {
                  type: 'object', name: 'scuola_sezione5_quote_righe', label: 'Sezione 5 — tabella quote', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.categoria || 'Nuova riga' }) },
                  fields: [
                    { type: 'string', name: 'categoria', label: 'Categoria', required: true },
                    { type: 'string', name: 'prezzo', label: 'Prezzo a settimana', required: true },
                    { type: 'string', name: 'categoria_en', label: '🇬🇧 Categoria (inglese)' },
                  ],
                },
                { type: 'string', name: 'scuola_sezione5_note', label: 'Sezione 5 — note/condizioni', list: true, required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione5_cta_label', label: 'Sezione 5 — etichetta bottone iscrizione', required: true },
                { type: 'string', name: 'scuola_sezione1_eyebrow_en', label: '🇬🇧 Sezione 1 — eyebrow (inglese)' },
                { type: 'string', name: 'scuola_sezione1_titolo_en', label: '🇬🇧 Sezione 1 — titolo (inglese)' },
                { type: 'string', name: 'scuola_sezione1_titolo_accent_en', label: '🇬🇧 Sezione 1 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'scuola_sezione1_lead_en', label: '🇬🇧 Sezione 1 — testo introduttivo (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_livelli_footer_testo_en', label: '🇬🇧 Testo dopo i livelli (inglese)' },
                { type: 'string', name: 'scuola_livelli_footer_link_label_en', label: '🇬🇧 Etichetta link (inglese)' },
                { type: 'string', name: 'scuola_sezione2_eyebrow_en', label: '🇬🇧 Sezione 2 — eyebrow (inglese)' },
                { type: 'string', name: 'scuola_sezione2_titolo_en', label: '🇬🇧 Sezione 2 — titolo (inglese)' },
                { type: 'string', name: 'scuola_sezione2_titolo_accent_en', label: '🇬🇧 Sezione 2 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'scuola_iscrizione_cta_label_en', label: '🇬🇧 Testo pulsante iscrizione (inglese)' },
                { type: 'string', name: 'scuola_sezione3_eyebrow_en', label: '🇬🇧 Sezione 3 — eyebrow (inglese)' },
                { type: 'string', name: 'scuola_sezione3_titolo_en', label: '🇬🇧 Sezione 3 — titolo (inglese)' },
                { type: 'string', name: 'scuola_sezione3_titolo_accent_en', label: '🇬🇧 Sezione 3 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'scuola_sezione3_badge_en', label: '🇬🇧 Sezione 3 — badge (inglese)' },
                { type: 'string', name: 'scuola_sezione3_paragrafo1_en', label: '🇬🇧 Sezione 3 — paragrafo 1 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione3_paragrafo2_en', label: '🇬🇧 Sezione 3 — paragrafo 2 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione3_paragrafo3_en', label: '🇬🇧 Sezione 3 — paragrafo 3 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione3_immagine_alt_en', label: '🇬🇧 Sezione 3 — immagine, alt (inglese)' },
                { type: 'string', name: 'scuola_sezione4_eyebrow_en', label: '🇬🇧 Sezione 4 — eyebrow (inglese)' },
                { type: 'string', name: 'scuola_sezione4_titolo_en', label: '🇬🇧 Sezione 4 — titolo (inglese)' },
                { type: 'string', name: 'scuola_sezione4_titolo_accent_en', label: '🇬🇧 Sezione 4 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'scuola_sezione4_footer_testo_en', label: '🇬🇧 Testo finale (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione5_eyebrow_en', label: '🇬🇧 Sezione 5 — eyebrow (inglese)' },
                { type: 'string', name: 'scuola_sezione5_titolo_en', label: '🇬🇧 Sezione 5 — titolo (inglese)' },
                { type: 'string', name: 'scuola_sezione5_titolo_accent_en', label: '🇬🇧 Sezione 5 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'scuola_sezione5_testo_en', label: '🇬🇧 Sezione 5 — testo introduttivo (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione5_note_en', label: '🇬🇧 Sezione 5 — note/condizioni (inglese)', list: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'scuola_sezione5_cta_label_en', label: '🇬🇧 Sezione 5 — etichetta bottone iscrizione (inglese)' },
              ],
            },
            {
              name: 'personal_trainer',
              label: 'Personal Trainer',
              fields: [
                ...heroSeoFields,
                { type: 'string', name: 'pt_sezione1_eyebrow', label: 'Sezione 1 — eyebrow', required: true },
                { type: 'string', name: 'pt_sezione1_titolo', label: 'Sezione 1 — titolo', required: true },
                { type: 'string', name: 'pt_sezione1_titolo_accent', label: 'Sezione 1 — titolo evidenziato', required: true },
                { type: 'string', name: 'pt_sezione1_paragrafo1', label: 'Sezione 1 — paragrafo 1', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'pt_sezione1_paragrafo2', label: 'Sezione 1 — paragrafo 2', required: true, ui: { component: 'textarea' } },
                {
                  type: 'object', name: 'pt_stats', label: 'Statistiche', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.numero ? `${item.numero} — ${item.etichetta || ''}` : 'Nuova statistica' }) },
                  fields: [
                    { type: 'string', name: 'numero', label: 'Numero/simbolo (es. "5", "1:1", "60\'", "∞")', required: true },
                    { type: 'string', name: 'etichetta', label: 'Etichetta (una riga per fascia)', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'etichetta_en', label: '🇬🇧 Etichetta (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'pt_sezione2_eyebrow', label: 'Sezione 2 — eyebrow', required: true },
                { type: 'string', name: 'pt_sezione2_titolo', label: 'Sezione 2 — titolo', required: true },
                { type: 'string', name: 'pt_sezione2_titolo_accent', label: 'Sezione 2 — titolo evidenziato', required: true },
                {
                  type: 'object', name: 'pt_trainers', label: 'Trainer', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.nome || 'Nuovo trainer' }) },
                  fields: [
                    { type: 'string', name: 'nome', label: 'Nome', required: true },
                    { type: 'image', name: 'foto', label: 'Foto (se assente, mostra un placeholder col nome)' },
                    { type: 'string', name: 'specializzazioni', label: 'Specializzazioni', list: true, required: true },
                    { type: 'string', name: 'qualifiche', label: 'Qualifiche e certificazioni', list: true, required: true },
                    { type: 'string', name: 'lingue', label: 'Lingue parlate (lascia vuoto per non mostrare la riga)', list: true },
                    { type: 'string', name: 'specializzazioni_en', label: '🇬🇧 Specializzazioni (inglese)', list: true },
                    { type: 'string', name: 'qualifiche_en', label: '🇬🇧 Qualifiche (inglese)', list: true },
                    { type: 'string', name: 'lingue_en', label: '🇬🇧 Lingue (inglese)', list: true },
                  ],
                },
                { type: 'string', name: 'pt_sezione3_eyebrow', label: 'Sezione 3 — eyebrow', required: true },
                { type: 'string', name: 'pt_sezione3_titolo', label: 'Sezione 3 — titolo', required: true },
                { type: 'string', name: 'pt_sezione3_titolo_accent', label: 'Sezione 3 — titolo evidenziato', required: true },
                {
                  type: 'object', name: 'pt_steps', label: 'Come funziona — step', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.titolo || 'Nuovo step' }) },
                  fields: [
                    { type: 'string', name: 'titolo', label: 'Titolo', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'pt_sezione4_titolo', label: 'CTA finale — titolo', required: true },
                { type: 'string', name: 'pt_sezione4_sottotitolo', label: 'CTA finale — sottotitolo', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'pt_sezione4_cta_label', label: 'CTA finale — testo pulsante', required: true },
                { type: 'string', name: 'pt_sezione1_eyebrow_en', label: '🇬🇧 Sezione 1 — eyebrow (inglese)' },
                { type: 'string', name: 'pt_sezione1_titolo_en', label: '🇬🇧 Sezione 1 — titolo (inglese)' },
                { type: 'string', name: 'pt_sezione1_titolo_accent_en', label: '🇬🇧 Sezione 1 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'pt_sezione1_paragrafo1_en', label: '🇬🇧 Sezione 1 — paragrafo 1 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'pt_sezione1_paragrafo2_en', label: '🇬🇧 Sezione 1 — paragrafo 2 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'pt_sezione2_eyebrow_en', label: '🇬🇧 Sezione 2 — eyebrow (inglese)' },
                { type: 'string', name: 'pt_sezione2_titolo_en', label: '🇬🇧 Sezione 2 — titolo (inglese)' },
                { type: 'string', name: 'pt_sezione2_titolo_accent_en', label: '🇬🇧 Sezione 2 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'pt_sezione3_eyebrow_en', label: '🇬🇧 Sezione 3 — eyebrow (inglese)' },
                { type: 'string', name: 'pt_sezione3_titolo_en', label: '🇬🇧 Sezione 3 — titolo (inglese)' },
                { type: 'string', name: 'pt_sezione3_titolo_accent_en', label: '🇬🇧 Sezione 3 — titolo evidenziato (inglese)' },
                { type: 'string', name: 'pt_sezione4_titolo_en', label: '🇬🇧 CTA finale — titolo (inglese)' },
                { type: 'string', name: 'pt_sezione4_sottotitolo_en', label: '🇬🇧 CTA finale — sottotitolo (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'pt_sezione4_cta_label_en', label: '🇬🇧 CTA finale — testo pulsante (inglese)' },
              ],
            },
            {
              name: 'preparazione_atletica',
              label: 'Preparazione Atletica',
              fields: [
                ...heroSeoFields,
                { type: 'string', name: 'prep_sala_eyebrow', label: 'Sala Attrezzi — eyebrow', required: true },
                { type: 'string', name: 'prep_sala_titolo', label: 'Sala Attrezzi — titolo', required: true },
                { type: 'string', name: 'prep_sala_titolo_accent', label: 'Sala Attrezzi — titolo evidenziato', required: true },
                { type: 'string', name: 'prep_sala_paragrafo1', label: 'Sala Attrezzi — paragrafo 1 (**grassetto**)', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'prep_sala_paragrafo2', label: 'Sala Attrezzi — paragrafo 2 (**grassetto**)', required: true, ui: { component: 'textarea' } },
                {
                  type: 'object', name: 'prep_sala_slideshow', label: 'Sala Attrezzi — slideshow foto', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.alt || 'Foto' }) },
                  fields: [
                    { type: 'image', name: 'immagine', label: 'Immagine', required: true },
                    { type: 'string', name: 'alt', label: 'Testo alternativo', required: true },
                    { type: 'string', name: 'alt_en', label: '🇬🇧 Testo alternativo (inglese)' },
                  ],
                },
                {
                  type: 'object', name: 'prep_sala_features', label: 'Sala Attrezzi — caratteristiche (ordine fisso, icone in codice)', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.titolo || 'Nuova caratteristica' }) },
                  fields: [
                    { type: 'string', name: 'titolo', label: 'Titolo', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true },
                    { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)' },
                  ],
                },
                { type: 'string', name: 'prep_sala_cta_label', label: 'Sala Attrezzi — testo link Personal Trainer', required: true },
                { type: 'string', name: 'prep_corsi_eyebrow', label: 'Corsi di Gruppo — eyebrow', required: true },
                { type: 'string', name: 'prep_corsi_titolo', label: 'Corsi di Gruppo — titolo', required: true },
                { type: 'string', name: 'prep_corsi_titolo_accent', label: 'Corsi di Gruppo — titolo evidenziato', required: true },
                { type: 'string', name: 'prep_corsi_sub', label: 'Corsi di Gruppo — testo introduttivo', required: true, ui: { component: 'textarea' } },
                {
                  type: 'object', name: 'prep_categorie', label: 'Categorie e corsi', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.label || 'Nuova categoria' }) },
                  fields: [
                    {
                      type: 'string', name: 'id', label: 'ID categoria (fisso, non cambiare)', required: true,
                      options: [
                        { value: 'endurance', label: 'endurance' },
                        { value: 'strength', label: 'strength' },
                        { value: 'balance', label: 'balance' },
                      ],
                    },
                    { type: 'string', name: 'label', label: 'Nome categoria', required: true },
                    { type: 'string', name: 'desc', label: 'Descrizione categoria', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'color', label: 'Colore (hex, es. #B83A00)', required: true },
                    { type: 'string', name: 'desc_en', label: '🇬🇧 Descrizione categoria (inglese)', ui: { component: 'textarea' } },
                    {
                      type: 'object', name: 'corsi', label: 'Corsi', list: true, required: true,
                      ui: { itemProps: (item) => ({ label: item?.nome || 'Nuovo corso' }) },
                      fields: [
                        { type: 'string', name: 'nome', label: 'Nome corso', required: true },
                        { type: 'string', name: 'durata', label: 'Durata (es. "60 min")', required: true },
                        { type: 'number', name: 'intensita', label: 'Intensità (numero da 1 a 3)', required: true },
                        { type: 'string', name: 'livello', label: 'Livello (es. "Tutti i livelli", "Intermedio")', required: true },
                        { type: 'string', name: 'desc', label: 'Descrizione', required: true, ui: { component: 'textarea' } },
                        { type: 'image', name: 'immagine', label: 'Immagine', required: true },
                        { type: 'string', name: 'nome_en', label: '🇬🇧 Nome corso (inglese)' },
                        { type: 'string', name: 'livello_en', label: '🇬🇧 Livello (inglese)' },
                        { type: 'string', name: 'desc_en', label: '🇬🇧 Descrizione (inglese)', ui: { component: 'textarea' } },
                      ],
                    },
                  ],
                },
                { type: 'string', name: 'prep_calendario_eyebrow', label: 'Calendario — eyebrow', required: true },
                { type: 'string', name: 'prep_calendario_titolo', label: 'Calendario — titolo', required: true },
                { type: 'string', name: 'prep_calendario_titolo_accent', label: 'Calendario — titolo evidenziato', required: true },
                { type: 'string', name: 'prep_calendario_sub', label: 'Calendario — testo introduttivo', required: true },
                { type: 'string', name: 'prep_sala_eyebrow_en', label: '🇬🇧 Sala Attrezzi — eyebrow (inglese)' },
                { type: 'string', name: 'prep_sala_titolo_en', label: '🇬🇧 Sala Attrezzi — titolo (inglese)' },
                { type: 'string', name: 'prep_sala_titolo_accent_en', label: '🇬🇧 Sala Attrezzi — titolo evidenziato (inglese)' },
                { type: 'string', name: 'prep_sala_paragrafo1_en', label: '🇬🇧 Sala Attrezzi — paragrafo 1 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'prep_sala_paragrafo2_en', label: '🇬🇧 Sala Attrezzi — paragrafo 2 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'prep_sala_cta_label_en', label: '🇬🇧 Sala Attrezzi — testo link (inglese)' },
                { type: 'string', name: 'prep_corsi_eyebrow_en', label: '🇬🇧 Corsi di Gruppo — eyebrow (inglese)' },
                { type: 'string', name: 'prep_corsi_titolo_en', label: '🇬🇧 Corsi di Gruppo — titolo (inglese)' },
                { type: 'string', name: 'prep_corsi_titolo_accent_en', label: '🇬🇧 Corsi di Gruppo — titolo evidenziato (inglese)' },
                { type: 'string', name: 'prep_corsi_sub_en', label: '🇬🇧 Corsi di Gruppo — testo introduttivo (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'prep_calendario_eyebrow_en', label: '🇬🇧 Calendario — eyebrow (inglese)' },
                { type: 'string', name: 'prep_calendario_titolo_en', label: '🇬🇧 Calendario — titolo (inglese)' },
                { type: 'string', name: 'prep_calendario_titolo_accent_en', label: '🇬🇧 Calendario — titolo evidenziato (inglese)' },
                { type: 'string', name: 'prep_calendario_sub_en', label: '🇬🇧 Calendario — testo introduttivo (inglese)' },
              ],
            },
            {
              name: 'tennis',
              label: 'Tennis',
              fields: [
                ...heroSeoFields,
                { type: 'string', name: 'tennis_campi_eyebrow', label: 'Sezione Campi — eyebrow', required: true },
                { type: 'string', name: 'tennis_campi_titolo', label: 'Sezione Campi — titolo', required: true },
                { type: 'string', name: 'tennis_campi_titolo_accent', label: 'Sezione Campi — titolo evidenziato', required: true },
                {
                  type: 'object', name: 'tennis_campi', label: 'Tipi di campo (foto non gestita da qui)', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.titolo || 'Nuovo campo' }) },
                  fields: [
                    { type: 'string', name: 'titolo', label: 'Titolo', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true },
                    { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)' },
                  ],
                },
                { type: 'string', name: 'tennis_soci_eyebrow', label: 'Sezione Soci — eyebrow', required: true },
                { type: 'string', name: 'tennis_soci_titolo', label: 'Sezione Soci — titolo', required: true },
                { type: 'string', name: 'tennis_soci_titolo_accent', label: 'Sezione Soci — titolo evidenziato', required: true },
                { type: 'string', name: 'tennis_soci_testo', label: 'Sezione Soci — testo (**grassetto**)', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'tennis_corsi_eyebrow', label: 'Sezione Corsi — eyebrow', required: true },
                { type: 'string', name: 'tennis_corsi_titolo', label: 'Sezione Corsi — titolo', required: true },
                { type: 'string', name: 'tennis_corsi_titolo_accent', label: 'Sezione Corsi — titolo evidenziato', required: true },
                { type: 'string', name: 'tennis_corsi_intro', label: 'Sezione Corsi — testo introduttivo (**grassetto**)', required: true, ui: { component: 'textarea' } },
                {
                  type: 'object', name: 'tennis_corsi_livelli', label: 'Sezione Corsi — livelli', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.titolo || 'Nuovo livello' }) },
                  fields: [
                    { type: 'string', name: 'titolo', label: 'Titolo', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true },
                    { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)' },
                  ],
                },
                { type: 'string', name: 'tennis_corsi_cta_label', label: 'Sezione Corsi — testo pulsante', required: true },
                { type: 'string', name: 'tennis_campi_eyebrow_en', label: '🇬🇧 Sezione Campi — eyebrow (inglese)' },
                { type: 'string', name: 'tennis_campi_titolo_en', label: '🇬🇧 Sezione Campi — titolo (inglese)' },
                { type: 'string', name: 'tennis_campi_titolo_accent_en', label: '🇬🇧 Sezione Campi — titolo evidenziato (inglese)' },
                { type: 'string', name: 'tennis_soci_eyebrow_en', label: '🇬🇧 Sezione Soci — eyebrow (inglese)' },
                { type: 'string', name: 'tennis_soci_titolo_en', label: '🇬🇧 Sezione Soci — titolo (inglese)' },
                { type: 'string', name: 'tennis_soci_titolo_accent_en', label: '🇬🇧 Sezione Soci — titolo evidenziato (inglese)' },
                { type: 'string', name: 'tennis_soci_testo_en', label: '🇬🇧 Sezione Soci — testo (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'tennis_corsi_eyebrow_en', label: '🇬🇧 Sezione Corsi — eyebrow (inglese)' },
                { type: 'string', name: 'tennis_corsi_titolo_en', label: '🇬🇧 Sezione Corsi — titolo (inglese)' },
                { type: 'string', name: 'tennis_corsi_titolo_accent_en', label: '🇬🇧 Sezione Corsi — titolo evidenziato (inglese)' },
                { type: 'string', name: 'tennis_corsi_intro_en', label: '🇬🇧 Sezione Corsi — testo introduttivo (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'tennis_corsi_cta_label_en', label: '🇬🇧 Sezione Corsi — testo pulsante (inglese)' },
              ],
            },
            {
              name: 'agonistica',
              label: 'Agonistica',
              fields: [
                ...heroSeoFields,
                { type: 'string', name: 'agonistica_metodo_eyebrow', label: 'Metodo — Eyebrow' },
                { type: 'string', name: 'agonistica_metodo_titolo', label: 'Metodo — Titolo' },
                { type: 'string', name: 'agonistica_metodo_titolo_accent', label: 'Metodo — Titolo evidenziato' },
                { type: 'string', name: 'agonistica_metodo_lead', label: 'Metodo — Testo introduttivo', ui: { component: 'textarea' } },
                { type: 'image', name: 'agonistica_metodo_immagine1', label: 'Metodo — Immagine 1' },
                { type: 'string', name: 'agonistica_metodo_immagine1_alt', label: 'Metodo — Immagine 1 (alt)' },
                { type: 'image', name: 'agonistica_metodo_immagine2', label: 'Metodo — Immagine 2' },
                { type: 'string', name: 'agonistica_metodo_immagine2_alt', label: 'Metodo — Immagine 2 (alt)' },
                {
                  type: 'object', name: 'agonistica_metodo_pillars', label: 'Metodo — Colonne', list: true,
                  ui: { itemProps: (item) => ({ label: item?.titolo || 'Nuova colonna' }) },
                  fields: [
                    { type: 'string', name: 'titolo', label: 'Titolo', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)', ui: { component: 'textarea' } },
                  ],
                },
                { type: 'string', name: 'agonistica_metodo_quote', label: 'Metodo — Citazione finale', ui: { component: 'textarea' } },
                { type: 'string', name: 'agonistica_punti_chiave_titolo', label: 'Punti chiave — Titolo box' },
                {
                  type: 'object', name: 'agonistica_punti_chiave', label: 'Punti chiave — Elenco', list: true,
                  ui: { itemProps: (item) => ({ label: item?.testo || 'Nuovo punto' }) },
                  fields: [
                    { type: 'string', name: 'testo', label: 'Testo', required: true },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)' },
                  ],
                },
                { type: 'string', name: 'agonistica_metodo_eyebrow_en', label: '🇬🇧 Metodo — Eyebrow (inglese)' },
                { type: 'string', name: 'agonistica_metodo_titolo_en', label: '🇬🇧 Metodo — Titolo (inglese)' },
                { type: 'string', name: 'agonistica_metodo_titolo_accent_en', label: '🇬🇧 Metodo — Titolo evidenziato (inglese)' },
                { type: 'string', name: 'agonistica_metodo_lead_en', label: '🇬🇧 Metodo — Testo introduttivo (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'agonistica_metodo_immagine1_alt_en', label: '🇬🇧 Metodo — Immagine 1 (alt, inglese)' },
                { type: 'string', name: 'agonistica_metodo_immagine2_alt_en', label: '🇬🇧 Metodo — Immagine 2 (alt, inglese)' },
                { type: 'string', name: 'agonistica_metodo_quote_en', label: '🇬🇧 Metodo — Citazione finale (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'agonistica_punti_chiave_titolo_en', label: '🇬🇧 Punti chiave — Titolo box (inglese)' },
                { type: 'string', name: 'agonistica_eyebrow', label: 'Eyebrow', required: true },
                { type: 'string', name: 'agonistica_titolo', label: 'Titolo', required: true },
                { type: 'string', name: 'agonistica_titolo_accent', label: 'Titolo evidenziato', required: true },
                {
                  type: 'object', name: 'agonistica_step', label: 'Percorso — step', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.titolo || 'Nuovo step' }) },
                  fields: [
                    { type: 'string', name: 'titolo', label: 'Titolo', required: true },
                    { type: 'string', name: 'testo', label: 'Testo', required: true },
                    { type: 'string', name: 'titolo_en', label: '🇬🇧 Titolo (inglese)' },
                    { type: 'string', name: 'testo_en', label: '🇬🇧 Testo (inglese)' },
                  ],
                },
                { type: 'string', name: 'agonistica_eyebrow_en', label: '🇬🇧 Eyebrow (inglese)' },
                { type: 'string', name: 'agonistica_titolo_en', label: '🇬🇧 Titolo (inglese)' },
                { type: 'string', name: 'agonistica_titolo_accent_en', label: '🇬🇧 Titolo evidenziato (inglese)' },
              ],
            },
            {
              name: 'torneo_avvenire',
              label: 'Torneo Avvenire',
              fields: [
                ...heroSeoFields,
                { type: 'string', name: 'torneo_quote_testo', label: 'Citazione', required: true },
                { type: 'string', name: 'torneo_quote_autore', label: 'Autore citazione', required: true },
                { type: 'string', name: 'torneo_storia_eyebrow', label: 'Sezione Storia — eyebrow', required: true },
                { type: 'string', name: 'torneo_storia_titolo', label: 'Sezione Storia — titolo', required: true },
                { type: 'string', name: 'torneo_storia_titolo_accent', label: 'Sezione Storia — titolo evidenziato', required: true },
                { type: 'string', name: 'torneo_storia_paragrafo1', label: 'Sezione Storia — paragrafo 1 (**grassetto**)', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'torneo_storia_paragrafo2', label: 'Sezione Storia — paragrafo 2 (**grassetto**)', required: true, ui: { component: 'textarea' } },
                {
                  type: 'object', name: 'torneo_stats', label: 'Statistiche', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.numero ? `${item.numero} — ${item.label || ''}` : 'Nuova statistica' }) },
                  fields: [
                    { type: 'string', name: 'numero', label: 'Numero (es. "60+", "U14")', required: true },
                    { type: 'string', name: 'label', label: 'Etichetta', required: true },
                    { type: 'string', name: 'label_en', label: '🇬🇧 Etichetta (inglese)' },
                  ],
                },
                { type: 'string', name: 'torneo_alumni_eyebrow', label: 'Sezione Alumni — eyebrow', required: true },
                { type: 'string', name: 'torneo_alumni_titolo', label: 'Sezione Alumni — titolo', required: true },
                { type: 'string', name: 'torneo_alumni_titolo_accent', label: 'Sezione Alumni — titolo evidenziato', required: true },
                { type: 'string', name: 'torneo_alumni_intro', label: 'Sezione Alumni — testo introduttivo', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'torneo_galleria_eyebrow', label: 'Sezione Galleria — eyebrow', required: true },
                { type: 'string', name: 'torneo_galleria_titolo', label: 'Sezione Galleria — titolo', required: true },
                { type: 'string', name: 'torneo_galleria_titolo_accent', label: 'Sezione Galleria — titolo evidenziato', required: true },
                { type: 'string', name: 'torneo_prossima_eyebrow', label: 'Sezione Prossima edizione — eyebrow', required: true },
                { type: 'string', name: 'torneo_prossima_titolo', label: 'Sezione Prossima edizione — titolo', required: true },
                { type: 'string', name: 'torneo_prossima_titolo_accent', label: 'Sezione Prossima edizione — titolo evidenziato', required: true },
                { type: 'string', name: 'torneo_prossima_testo', label: 'Sezione Prossima edizione — testo', required: true, ui: { component: 'textarea' } },
                { type: 'string', name: 'torneo_quote_testo_en', label: '🇬🇧 Citazione (inglese)' },
                { type: 'string', name: 'torneo_quote_autore_en', label: '🇬🇧 Autore citazione (inglese)' },
                { type: 'string', name: 'torneo_storia_eyebrow_en', label: '🇬🇧 Sezione Storia — eyebrow (inglese)' },
                { type: 'string', name: 'torneo_storia_titolo_en', label: '🇬🇧 Sezione Storia — titolo (inglese)' },
                { type: 'string', name: 'torneo_storia_titolo_accent_en', label: '🇬🇧 Sezione Storia — titolo evidenziato (inglese)' },
                { type: 'string', name: 'torneo_storia_paragrafo1_en', label: '🇬🇧 Sezione Storia — paragrafo 1 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'torneo_storia_paragrafo2_en', label: '🇬🇧 Sezione Storia — paragrafo 2 (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'torneo_alumni_eyebrow_en', label: '🇬🇧 Sezione Alumni — eyebrow (inglese)' },
                { type: 'string', name: 'torneo_alumni_titolo_en', label: '🇬🇧 Sezione Alumni — titolo (inglese)' },
                { type: 'string', name: 'torneo_alumni_titolo_accent_en', label: '🇬🇧 Sezione Alumni — titolo evidenziato (inglese)' },
                { type: 'string', name: 'torneo_alumni_intro_en', label: '🇬🇧 Sezione Alumni — testo introduttivo (inglese)', ui: { component: 'textarea' } },
                { type: 'string', name: 'torneo_galleria_eyebrow_en', label: '🇬🇧 Sezione Galleria — eyebrow (inglese)' },
                { type: 'string', name: 'torneo_galleria_titolo_en', label: '🇬🇧 Sezione Galleria — titolo (inglese)' },
                { type: 'string', name: 'torneo_galleria_titolo_accent_en', label: '🇬🇧 Sezione Galleria — titolo evidenziato (inglese)' },
                { type: 'string', name: 'torneo_prossima_eyebrow_en', label: '🇬🇧 Sezione Prossima edizione — eyebrow (inglese)' },
                { type: 'string', name: 'torneo_prossima_titolo_en', label: '🇬🇧 Sezione Prossima edizione — titolo (inglese)' },
                { type: 'string', name: 'torneo_prossima_titolo_accent_en', label: '🇬🇧 Sezione Prossima edizione — titolo evidenziato (inglese)' },
                { type: 'string', name: 'torneo_prossima_testo_en', label: '🇬🇧 Sezione Prossima edizione — testo (inglese)', ui: { component: 'textarea' } },
              ],
            },
            {
              name: 'regolamento',
              label: 'Regolamento del Club',
              fields: [
                ...heroSeoFields,
                {
                  type: 'string', name: 'regolamento_body', label: 'Testo regolamento (italiano)', required: true,
                  ui: { component: 'textarea' },
                  description: 'Usa "## " per un titolo di sezione, "### " per un sottotitolo, "- " per un elenco puntato, riga vuota per andare a capo tra paragrafi, "**testo**" per il grassetto.',
                },
                { type: 'string', name: 'regolamento_body_en', label: '🇬🇧 Testo regolamento (inglese)', ui: { component: 'textarea' } },
              ],
            },
            {
              name: 'privacy',
              label: 'Privacy Policy',
              fields: [
                ...heroSeoFields,
                {
                  type: 'string', name: 'privacy_body', label: 'Testo privacy policy (italiano)', required: true,
                  ui: { component: 'textarea' },
                  description: 'Usa "## " per un titolo di sezione, "### " per un sottotitolo, "- " per un elenco puntato, riga vuota per andare a capo tra paragrafi, "**testo**" per il grassetto.',
                },
                { type: 'string', name: 'privacy_body_en', label: '🇬🇧 Testo privacy policy (inglese)', ui: { component: 'textarea' } },
              ],
            },
            {
              name: 'partners',
              label: 'Partners',
              fields: [
                ...heroSeoFields,
                {
                  type: 'object', name: 'partners_lista', label: 'Partner', list: true, required: true,
                  ui: { itemProps: (item) => ({ label: item?.nome || 'Nuovo partner' }) },
                  fields: [
                    { type: 'string', name: 'nome', label: 'Nome', required: true },
                    { type: 'string', name: 'descrizione', label: 'Descrizione', required: true, ui: { component: 'textarea' } },
                    { type: 'string', name: 'descrizione_en', label: '🇬🇧 Descrizione (inglese)', ui: { component: 'textarea' } },
                    { type: 'image', name: 'logo', label: 'Logo', required: true },
                    { type: 'string', name: 'sito', label: 'Sito web (URL completo)', required: true },
                  ],
                },
              ],
            },
          ],
        };
      })(),
    ],
  },
});
